---
# Playbook qui déploies l'ensemble des roles (all, webservers, ...)

- hosts: all
  remote_user: root

  vars_files:
    - ./roles/all/vars/vars.yml

  roles:
    - all

- hosts: webservers
  remote_user: root

  vars_files:
    - ./roles/webserver/vars/vars.yml

  roles:
    - webserver

- hosts: database
  remote_user: root

  vars_files:
    - ./roles/db/vars/vars.yml

  roles:
    - db
