---
  # Installation de MySQL Server et de phpmyadmin

  - name: install_mysql-server
    apt: name=mysql-server state=present update_cache=yes
    notify:
      - restart_mysql

  - name: install_phpmyadmin
    apt: phpmyadmin state=present update_cache=yes

  - name: lien_symbolique_phpmyadmin
    command: ln -s /usr/share/phpmyadmin /var/www/phpmyadmin
