---
  - name: start_mysql
    service: name=mysql state=started enabled=yes

  - name: stop_mysql
    service: name=mysql state=stoped

  - name: restart_mysql
    service: name=mysql state=restarted enabled=yes
