---
  # Installe la partie webserver ( apache2 + php5 )

  - name: Install apache2
    apt: name=apache2 state=present

  - name: Install PHP module for apache2
    apt: name={{ items }} state=present
    with_items:
      - php5
      - php5-mysql
